# config for your inklings program

logs:
  dir: "logs"
  actions: "actions.txt"

simulation:
  default_rows: 8
  default_cols: 8
  min_rows: 20
  min_cols: 20
  min_threads: 8
  default_threads: 4
  draw_colored_traveler_heads: true

ink:
  max_level: 50
  max_add_ink: 10
  refill_ink: 10
  initial_red_level: 20
  initial_green_level: 10
  initial_blue_level: 40

timing:
  min_producer_sleep_us: 30000
  producer_sleep_us: 100000
  inkling_sleep_us: 1000000
  inkling_sleep_step_us: 100000
  inkling_sleep_min_us: 0
  inkling_sleep_max_us: 2147483647
  arg_warning_sleep_s: 2
  shutdown_delay_s: 30
  event_loop_interval_ms: 1000
  event_loop_sleep_s: 1

event_loop:
  max_recursive_depth: 5

producers:
  speedup_factor_num: 8
  speedup_factor_den: 10
  slowdown_factor_num: 12
  slowdown_factor_den: 10

io:
  pipe_path: "/tmp/my_pipe"

ui:
  icon_directions:
    north: "\u2191"
    west:  "\u2190"
    south: "\u2193"
    east:  "\u2192"
    none:  " "
  messages:
    ink_tank_header: "Ink Tank Levels, the MAX is: "
    live_threads_label: "Live Threads: "
    no_args_message: "No arguments provided, running with 8x8 grid and 4 threads.\n\tThis message will dissapear in 2 seconds... \n"
    quit_no_threads_message: "drawState callint it quits, no threads left..."
    quit_esc_message: "I see you pressed ESC, game over..."
    quit_generic_message: "Somebody called quits, goodbye sweet digital world, this was their message: "
